### ISSUE TITLE
Add support for Laravel 11

### ISSUE THREAD

**Issue by ljsharp** [laravelcm/laravel-subscriptions#12]
Could you kindly incorporate support for Laravel 11, please? Thanks

**Comment by saifnbdev** [comment]
Any updates on this ?

**Comment by humanatepixel** [comment]
In the meantime, there is https://github.com/bpuig/laravel-subby which supports laravel 11 :+1:

**Comment by humanatepixel** [comment]
+1

**Comment by khalidsheet** [comment]
+1

**Comment by Zebedeu** [comment]
+1

**Comment by khalidsheet** [comment]
Do you know if this package is still maintained or should we create a new one?

**Comment by humanatepixel** [comment]
This is a good alternative https://github.com/lucasdotvin/laravel-soulbscription

**Comment by Zebedeu** [comment]
> Esta é uma boa alternativa. https://github.com/lucasdotvin/laravel-soulbscription

I'll test this approach as it seems to be a promising solution. Thank you.

**Comment by mckenziearts** [comment]
Laravel 11 is now supported #16
