### ISSUE TITLE
Call to undefined method Laravelcm\Subscriptions\Models\Plan::planSubscriptions()

### ISSUE THREAD

**Issue by IsbosetA** [laravelcm/laravel-subscriptions#13]
This error is in Model Plan,

```
protected static function boot(): void
    {
        parent::boot();

        static::deleted(function (Plan $plan): void {
            $plan->features()->delete();
            $plan->planSubscriptions()->delete();
        });
    }

```
For solved it you only need to change 
` $plan->planSubscriptions()->delete();`
to
` $plan->subscriptions()->delete();`
This error ocurred when you use `$plan->delete();` method

**Comment by evokelektrique** [comment]
I have the same issue in Laravel 10

**Comment by IsbosetA** [comment]
> I have the same issue in Laravel 10

this is the solution

For solved it you only need to change
 $plan->planSubscriptions()->delete();
to
 $plan->subscriptions()->delete();
This error ocurred when you use $plan->delete(); method

the error ocurred for de fuction name

**Comment by mckenziearts** [comment]
Fix on the newest release. Thank you
