### ISSUE TITLE
There are no commands defined in the "publish" namespace

### ISSUE THREAD

**Issue by alex8bits** [laravelcm/laravel-subscriptions#7]
When executing command "php artisan publish:laravel-subscriptions" I`m getting error:

"There are no commands defined in the "publish" namespace."

**Comment by capamaroux1** [comment]
Same error for me too. Tested on Laravel 10

**Comment by mkh71** [comment]
use php artisan vendor:publish --provider="Laravelcm\Subscriptions\SubscriptionServiceProvider"
