### ISSUE TITLE
Question about this project

### ISSUE THREAD

**Issue by davidmartinrius** [laravelcm/laravel-subscriptions#9]
What difference is there between [Laravel Cashier](https://laravel.com/docs/10.x/billing)  and this project?

**Comment by mckenziearts** [comment]
Laravel Cashier only lets you add 2 types of payment providers (Stripe and Paddle), so the aim of this project is to offer the possibility of having the entire subscription management system and adding several other payment methods other than Stripe or Paddle.

**Comment by davidmartinrius** [comment]
Great! Is there a way to mate it work with Redsys? Is there any documentation on how integrate it? Thank you @mckenziearts

**Comment by mckenziearts** [comment]
Personally, I don't know Redsys., but here's a mini example of integration I had to do on a project


```php
public function subscribe(SubscribeRequest $request): JsonResponse
{
  /** @var Plan $plan */
  $plan = Plan::find($request->input('plan_id'));
  /** @var User $user */
  $user = User::canSubscribe()->find($request->input('user_id'));

  if (! $user) {
      return $this->errorResponse(__('You cannot subscribe to this plan. Your account may have a problem'));
  }

  if ($user->subscribedPlans()->isNotEmpty()) {
      return $this->errorResponse(__('You already have a subscription!'));
  }

  $action = $user->planSubscriptions->isNotEmpty() ? SubscriptionAction::RENEW : SubscriptionAction::SUBSCRIBE;

  // here your own integration of your payment solution
  $response = ProceedPayment::run($user, $plan, $action);

  return $this->successResponse(__('Your payment is in progress...'), $response);
}
```

It was for the integration of a simple mobile money solution. I don't know if the example helps, but it's just to add the package actions after payment. 

Compared to Laravel Cashier, which handles all this in back, here you'll have to set up the whole payment, re-subscription and trial period process yourself for everything to work properly.

And if your solution uses webhooks to validate a payment, you'll have to set it up for the whole system to work.

**Comment by davidmartinrius** [comment]
Well, i think there were a missunderstood, maybe I did not provide enough information at the beginning . I think the example you provided is not what I was talking about.
Redsys is like Stripe or Paddle. It is another bank and it has its payment method. I meant if there is a straightforward way to integrate payment methods from other banks.

**Comment by mckenziearts** [comment]
To integrate another solution, you need to integrate the bank's sdk yourself (php or Laravel). The aim of the package is just to give the subscription and renewal methods and to give the developer complete control to add any means (even Stripe if he wants).

**Comment by davidmartinrius** [comment]
ok, good to know, thanks for clarifying.
